### ISSUE TITLE
DEVirion fails to load virions when using PM4-beta release even virion's declared API is 4.0.0

### ISSUE THREAD

**Issue by alvin0319** [poggit/devirion#16]
![image](https://user-images.githubusercontent.com/32565818/133375144-86017ebe-0285-4f14-88ce-cd58826f57de.png)

**Comment by SOF3** [comment]
Fix: change this to use the PocketMine API for checking versions. https://github.com/poggit/devirion/blob/f73ac84a9e454fb9f97cdaaa53bc5cc44b4c082c/src/poggit/virion/devirion/DEVirion.php#L171

**Comment by inxomnyaa** [comment]
https://github.com/WolvesFortress/devirion/commit/41a530e988982119c9971b16ffb4b1aa3131a568

This was my fix, not sure if it is correct. Shall i PR?

**Comment by SOF3** [comment]
Isn't there a method in PluginManager for detecting that?

**Comment by alvin0319** [comment]
> Isn't there a method in PluginManager for detecting that?

Yes, there is `ApiVersion::isCompatible()` method to compare APIs

**Comment by alvin0319** [comment]
I fixed and simplified API checking like this:
![image](https://user-images.githubusercontent.com/32565818/133632748-96ce84c6-b689-4d99-a9dd-a23969e7b5a5.png)
but I don't know this is a correct way.

**Comment by SOF3** [comment]
> I fixed and simplified API checking like this:
> ![image](https://user-images.githubusercontent.com/32565818/133632748-96ce84c6-b689-4d99-a9dd-a23969e7b5a5.png)
> but I don't know this is a correct way.

Issue trackers are not code review, and screenshots are not patches. If you have made an idea and want to know if it's good, why not go create a pull request straight away?

**Comment by AIPTU** [comment]
I still get this issue when using build https://github.com/poggit/devirion/commit/dc938f47da69cfc50a832e4ddf2de322ef87b269
```
[Server thread/ERROR]: [DEVirion] Cannot load virion Commando: Server has incompatible API version 4.0.0-BETA3
```
Server version: 4.0.0-BETA3+dev (git hash: 87dc763d924c4221f599fad4bcd35e9cadbc72a7-dirty)

**Comment by SOF3** [comment]
@alvin0319 any insights about @AIPTU's comment?
